apiVersion: v1
items:
- apiVersion: source.toolkit.fluxcd.io/v1
  kind: GitRepository
  metadata:
    name: rke-helm-charts
    namespace: flux-system
  spec:
    interval: 1m0s
    ref:
      branch: main
    secretRef:
      name: flux-system
    timeout: 60s
    url: https://github.com/mustafa-abdelnasser/rke-helm-charts.git
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 1m
  chart:
    spec:
      chart: "sealed-secrets"
      sourceRef:
        kind: GitRepository
        name: rke-helm-charts
        namespace: flux-system
  values:
    namespace: "sealed-secrets"
