apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 1m
  releaseName: sealed-secrets
  chart:
    spec:
      chart:
        path: fluxcd/sealed-secrets
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    namespace: "sealed-secrets"
