apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-kafka
  namespace: kafka
spec:
  interval: 1m
  chart:
    spec:
      chart: strimzi-kafka-operator
      sourceRef:
        kind: GitRepository
        name: rke-helm-charts
        namespace: flux-system
      values:
        replicas: 1