apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed
  namespace: sealed-secrets-controller
spec:
  interval: 1m
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: GitRepository
        name: rke-helm-charts
        namespace: flux-system